version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: todolist-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 114514
      MYSQL_DATABASE: todolist
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todolist-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:6.2
    container_name: todolist-redis
    command: redis-server --requirepass 114514
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - todolist-network

  todolist-backend:
    build: .
    container_name: todolist-backend
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    networks:
      - todolist-network

  nginx:
    image: nginx:1.21
    container_name: todolist-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - todolist-backend
    networks:
      - todolist-network

networks:
  todolist-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: 