mybatis-plus:
  # xml地址
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名法
    map-underscore-to-camel-case: true

todolist:
  # mysql
  mysql:
    ip: 116.62.189.123
    port: 3306
    db: todolist
    username: root
    password: 114514
  # redis
  redis:
    host: 116.62.189.123
    port: 6379
    password: 114514
